---
- name: Check for lpass in path
  command: which lpass
- name: Verify user is logged into lastpass-cli
  shell: lpass ls
- name: Check for MariaDB root credentials
  shell: >
    lpass show 'd7\mariadb/mariadb-root' | grep Username | cut -d ' ' -f 2 | xargs
  register: mariadb_get_root_user
- name: Set MariaDB root credentials
  shell: >
    lpass generate --sync=now --username=root 'd7\mariadb/mariadb-root' --no-symbols 32
  register: mariadb_set_root_pw
  when: mariadb_get_root_user.stdout != 'root'
- name: Fetch MariaDB root credentials
  shell: >
    lpass show --sync=now 'd7\mariadb/mariadb-root' | grep Password | cut -d ' ' -f 2 | xargs
  register: mariadb_get_root_pw
- name: Set MariaDB root password as fact
  set_fact:
    mariadb_root: "{{ mariadb_get_root_pw.stdout }}"
